### PR TITLE
empty manifest.js file

### PR DESCRIPTION
**Pull request by diosat91**
Solution for https://github.com/igorkasyanchuk/any_login/issues/52

### CODE REVIEW

**Comment by rbclark** [comment]
@diosat91 This seems reasonable, one question: were you able to test it locally to ensure that it fixed your issue?

**Comment by diosat91** [comment]
Sorry, the PR was a little premature. No, it doesn't actually fix the issue. Our tests pass but the gem doesn't work with this fix. It can't find the 'any_login/person.png'. I'll close this.

**Comment by rbclark** [comment]
@diosat91 This gem should no longer require `any_login/person.png`, we've updated it to use an SVG file that is loaded from a partial.

**Comment by igorkasyanchuk** [comment]
yeap looks like you have an old fork. We don't have that image anymore.

**Pull request closed without merging**
