### PR TITLE
Remove trailing carriage returns and add new lines

### PR DESCRIPTION
**Pull request by incubus**

### CODE REVIEW

**Comment by igorkasyanchuk** [comment]
Do we have problem with it?
I know that according to ruby style guide https://github.com/styleguide/ruby and some gems like rubocop new line is a good practice
Why you want to remove it?

**Comment by incubus** [comment]
I want to remove Windows carriage returns and **add** new lines.

**Comment by incubus** [comment]
Please take a look on your lib/generators/any_login/templates/any_login.rb (Windows carriage returns exists) or test/dummy-authlogic/app/models/user_session.rb (no new line) for example.

**Comment by igorkasyanchuk** [comment]
Okay, please create new PR with this fix. Thanks

**Pull request closed without merging**
