### PR TITLE
Multiple models support

### PR DESCRIPTION
**Pull request by kenzo-tanaka**
## Overview
I thought it's useful if any_login supports multiple model. And I found some issues to request it.So I tried it in this PR. 
I changed many files, so if you don't like this support please close this PR😅

## What I fixed

- Accept multiple model setting by `klass_names`
- Display multiple login forms
- Pass class name by `params[:as]`
- In controller, find model name by `params[:as]` and login.

## Demo

https://user-images.githubusercontent.com/33926355/128660436-7e2ca55c-17fa-4e2e-aed6-498177ad5fac.mov

### CODE REVIEW

**Comment by rbclark** [comment]
@kenzo-tanaka Thank you for this PR! I'd really like to get it merged if possible, would you be able to deconflict this and perhaps update the test applications to utilize this behavior for testing purposes?

**Comment by kenzo-tanaka** [comment]
@rbclark
Thanks for the reply! OK, I will try it.

**Comment by kenzo-tanaka** [comment]
@rbclark 
Could you please tell me how to run the test application? When I run `bundle exec rake test`, this error occurred.

```
rake aborted!
NoMethodError: undefined method `new' for BigDecimal:Class
/Users/tanakakenzou/Documents/personal/any_login/test/dummy/config/application.rb:3:in `require'
/Users/tanakakenzou/Documents/personal/any_login/test/dummy/config/application.rb:3:in `<top (required)>'
/Users/tanakakenzou/Documents/personal/any_login/test/dummy/Rakefile:4:in `require'
/Users/tanakakenzou/Documents/personal/any_login/test/dummy/Rakefile:4:in `<top (required)>'
/Users/tanakakenzou/Documents/personal/any_login/Rakefile:18:in `load'
/Users/tanakakenzou/Documents/personal/any_login/Rakefile:18:in `<top (required)>'
/Users/tanakakenzou/.rbenv/versions/2.7.3/bin/bundle:23:in `load'
/Users/tanakakenzou/.rbenv/versions/2.7.3/bin/bundle:23:in `<main>'
Tasks: TOP => load_app
(See full trace by running task with --trace)
```

**Comment by igorkasyanchuk** [comment]
Hello @kenzo-tanaka 
Please try to merge current master into your branch. And send PR again, I think this time it will execute tests in GIthub Actions.

**Comment by rbclark** [comment]
@kenzo-tanaka The test suite it broken out into 4 different rake tasks due to conflicts when trying to load multiple apps for testing at once. The tasks are 

```
bundle exec rake test_authlogic
bundle exec rake test_clearance
bundle exec rake test_devise
bundle exec rake test_sorcery
```

**Comment by kenzo-tanaka** [comment]
It's difficult to resolve conflict. So I would like to create a new pull request🙏
https://github.com/igorkasyanchuk/any_login/pull/54

**Pull request closed without merging**
